Controllers/LopController.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace btl_tkweb.Controllers
{
    public class LopController : Controller
    {
        private readonly UserManager<AccountUser> _userManager;
        SchoolContext db;
        public LopController(SchoolContext db, UserManager<AccountUser> userManager)
        {
            this.db = db;
            _userManager = userManager;
        }
        private AccountUser getUser() { return _userManager.GetUserAsync(HttpContext.User).Result; }

        public IActionResult Index()
        {
            var user = getUser();
            if (user == null) return NotFound();
            if (user.role == AccountUser.ADMIN)
            {
                var lop = db.Lop.Include(s => s.dshs).ToList();
                return View(lop);
            }
            if (user.role == AccountUser.GIAOVIEN)
            {
                var lop = db.Lop.Include(l => l.ctgd).Include(s => s.dshs).Where(l=>l.ctgd.Any(ct=>ct.GiaoVienID==user.Id));
                return View(lop);
            }
            if (user.role == AccountUser.HOCSINH)
            {
                var lop = db.Lop.Include(s => s.dshs).Where(l=>l.LopID==((HocSinh)user).LopID);
                return View(lop);
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult Create()
        {
            var user = getUser();
            if(user!=null && user.role==AccountUser.ADMIN)
                return View();
            else
                return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("LopID", "GVCN")] Lop lop)
        {
            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (ModelState.IsValid)
                {
                    db.Lop.Add(lop);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (id == null) return NotFound();
                var lop = db.Lop.Find(id);
                if (lop == null)
                {
                    return NotFound();
                }
                ViewBag.LopId = id;
                return View();
            }
            return NotFound();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string oldid, [Bind("LopID","GVCN")] Lop lop)
        {

            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (oldid == null || db.Lop.Find(oldid) == null)
                {
                    return NotFound();
                }
                ViewBag.LopId = oldid;
                if (ModelState.IsValid)
                {

                    db.Add(lop);
                    db.SaveChanges();
                    foreach (var item in db.ChiTietGiangDay)
                    {
                        if (item.LopId == oldid)
                        {
                            item.LopId = lop.LopID;
                            db.Update(item);
                        }
                    }
                    db.SaveChanges();
                    foreach (var item in db.HocSinh)
                    {
                        if (item.LopID == oldid)
                        {
                            item.LopID = lop.LopID;
                            db.Update(item);
                        }
                    }
                    db.SaveChanges();
                    db.Lop.Remove(db.Lop.Find(oldid));
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {

            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (id == null) return NotFound();
                var lop = db.Lop.Find(id);
                if (lop == null) return NotFound();
                return View(lop);
            }
            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(string id)
        {

            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (id == null) return NotFound();
                var lop = db.Lop.Include(l => l.dshs).Where(l => l.LopID == id);
                if (lop.Count() == 0) return NotFound();
                foreach (var item in lop.First().dshs)
                {
                    item.deleteBangDiem(db);
                    db.SaveChanges();
                    db.Remove(item);
                    db.SaveChanges();
                }
                foreach (var item in lop.First().ctgd)
                {
                    db.Remove(item);
                }
                db.Lop.Remove(lop.First());
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

Controllers/MonHocController.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace btl_tkweb.Controllers
{
    public class MonHocController : Controller
    {
        private readonly UserManager<AccountUser> _userManager;
        SchoolContext db;
        public MonHocController(SchoolContext db, UserManager<AccountUser> userManager)
        {
            this.db = db;
            _userManager = userManager;
        }
        private AccountUser getUser() { return _userManager.GetUserAsync(HttpContext.User).Result; }
        public IActionResult Index()
        {
            var user = getUser();
            if (user == null) return NotFound();

            var monhoc = db.MonHoc.ToList();
            return View(monhoc);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("TenMon", "HeSoMon")] MonHoc mon)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (ModelState.IsValid)
            {
                db.MonHoc.Add(mon);
                db.SaveChanges();
                foreach(var item in db.HocSinh)
                {
                    db.DiemSo.Add(new DiemSo() { HocSinhId = item.Id, MonHocID = mon.MonHocID});
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Edit(int id)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (id == null || db.MonHoc == null) return NotFound();
            var mon = db.MonHoc.Find(id);
            if (mon == null) return NotFound();
            return View(mon);
        }

        [HttpPost]
        public IActionResult Edit(int id, [Bind("MonHocID", "TenMon", "HeSoMon")] MonHoc mon)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (id != mon.MonHocID)
            {
                return Content(id+" "+mon.MonHocID);
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(mon);
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Gvexist(mon.MonHocID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(mon);
        }
        private bool Gvexist(int id)
        {
            return (db.MonHoc?.Any(e => e.MonHocID == id)).GetValueOrDefault();
        }

        public IActionResult Delete(int id)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (id == null || db.MonHoc == null)
            {
                return NotFound();
            }
            var mon = db.MonHoc.Include(m=>m.GiaoViens).FirstOrDefault(m => m.MonHocID == id);
            if (mon == null)
            {
                return NotFound();
            }
            if (mon.GiaoViens.Count() > 0)
            {
                return Content("Môn học này còn giáo viên chưa xóa!");
            }
            return View(mon);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (db.MonHoc == null)
            {
                return Problem("Không còn môn học");
            }
            var mon = db.MonHoc.Find(id);
            if (mon != null)
            {
                db.MonHoc.Remove(mon);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

ViewComponents/LeftMenuViewComponent.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace btl_tkweb.ViewComponents
{
    public class LeftMenuViewComponent : ViewComponent
    {
        SchoolContext _context;
        UserManager<AccountUser> UserManager;
        private List<MenuItem> MenuItems = new List<MenuItem>();
        public LeftMenuViewComponent(
            SchoolContext context, 
            UserManager<AccountUser> UserManager
        )
        {
            _context = context;
            this.UserManager = UserManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await UserManager.GetUserAsync(HttpContext.User);
            MenuItems.Add(new MenuItem() { Name = "Home" ,controllerName="Home",actionName="Index"});
            if(user != null )
            {
                MenuItems.Add(new MenuItem() { Name = "Danh sách lớp" ,controllerName="Lop",actionName="Index"});
                MenuItems.Add(new MenuItem() { Name = "Môn học" ,controllerName="MonHoc",actionName="Index"});
                MenuItems.Add(new MenuItem() { Name = "Danh sách giáo viên" ,controllerName="GiaoVien",actionName="Index"});
                if (user.role==AccountUser.ADMIN)
                    MenuItems.Add(new MenuItem() { Name = "Danh sách học sinh", controllerName = "HocSinh", actionName = "Index" });

            }

            return View("DefaultLeftMenu", MenuItems);
        }
    }
}
 

Views/Shared/CollapsingNav.cshtml
<nav class="navbar justify-content-start navbar-dark bg-dark">
    <div class="d-inline">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-controls="collapseWidthExample" aria-expanded="false" >
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <a class="navbar-brand flex-grow-1" href="#">
        Quản lý điểm học sinh
    </a>
    <div class="me-3">
        <partial name="_LoginPartial"/>
    </div>
</nav>

Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body >
    <main style ="height:100vh;display:flex; flex-direction:column;">
        <partial name="CollapsingNav" />
        <main style="display:flex;flex-grow:1;height:100%;overflow: clip;">
            <!-- Begin nav -->
            <partial name="SlidebarNav" />
            <!-- End nav -->

            <div id="layoutContent" style="flex-grow:1;overflow-y: auto;">
                <!-- Begin Right content -->
                <div id="layoutSidenav_content">
                    <!-- Begin Main -->
                    <main>
                        <div class="shadow p-3">
                            <h1>@ViewData["Title"]</h1>
                        </div>
                        <div class="m-3">
                            @RenderBody()

                        </div>
                        @RenderSection("scripts", required: false)
                    </main>
                    <!-- End Main -->
                </div>
                <!-- End Right content -->
            </div>
        </main>
    </main>
</body>
</html>

Views/Shared/MyLayout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <main style="height:100vh;display:flex; flex-direction:column;">
        <partial name="CollapsingNav" />
        <main style="display:flex;flex-grow:1;height:100%;overflow: clip;">
            <!-- Begin nav -->
            @await Component.InvokeAsync("LeftMenu");
            <!-- End nav -->

            <div id="layoutContent" style="flex-grow:1;overflow-y: auto;">
                <!-- Begin Right content -->
                <div id="layoutSidenav_content">
                    <!-- Begin Main -->
                    <main>
                        <div class="shadow p-3">
                            <h1>@ViewData["Title"]</h1>
                        </div>
                        <div class="m-3">
                            @RenderBody()

                        </div>
                        @RenderSection("scripts", required: false)
                    </main>
                    <!-- End Main -->
                </div>
                <!-- End Right content -->
            </div>
        </main>
    </main>
</body>
</html>

Views/Shared/SlidebarNav.cshtml
<div class=" collapse collapse-horizontal" id="collapseWidthExample" >
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;height:100%;">
        @* <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Menu</span>
        </a>
        <hr> *@
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="btn btn-dark">
                <a asp-controller="Home" asp-action="Index" class="nav-link text-white" aria-current="page">
                    Trang chủ
                </a>
            </li>
            <li class=" btn btn-dark">
                <a asp-controller="Lop" asp-action="Index" class="nav-link text-white">
                    Danh sách lớp
                </a>
            </li>
            <li class="btn btn-dark">
                <a asp-controller="GiaoVien" asp-action="Index" class="nav-link text-white">
                    Danh sách giáo viên
                </a>
            </li>
            <li class="btn btn-dark">
                <a asp-controller="MonHoc" asp-action="Index" class="nav-link text-white">
                    Danh sách môn học
                </a>
            </li>
            <li class="btn btn-dark">
                <a asp-controller="HocSinh" asp-action="Index" class="nav-link text-white">
                    Danh sách học sinh
                </a>
            </li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - btl_tkweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/btl_tkweb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">btl_tkweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - btl_tkweb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>