Models/HocSinh.cs
using btl_tkweb.Data;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Text;
using System.Text.RegularExpressions;

namespace btl_tkweb.Models
{
    public class HocSinh : AccountUser
    {
        public static int count=0;
        public HocSinh() {
            DiemSo=new HashSet<DiemSo>();
            role = HOCSINH;
            count++;
            HocSinhID = count;
        }
        public int HocSinhID { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string HoVaTen { get { return Ho + " " + Ten; } }
        public bool Nu { get; set; }
        public DateTime NgaySinh { get; set; }
        public string LopID { get; set; }
        public virtual Lop? Lop { get; set; }
        public string? GhiChu { get; set; }
        public string Username { get { 
            string user = "HS";
            string HoVaTen = Ho + Ten;
            for (int i = 0; i < HoVaTen.Length; i++)
            {
                if (HoVaTen[i] == ' ') continue;
                user += HoVaTen[i];
            }
            user += HocSinhID;
            return removeUnicode.RemoveUnicode(user);
        } }
        public virtual ICollection<DiemSo> DiemSo { get; set; }

        public void createBangDiem(SchoolContext db)
        {
            foreach (var mon in db.MonHoc)
            {
                DiemSo d = new DiemSo() { MonHocID = mon.MonHocID, HocSinhId = this.Id };
                db.Add(d);
            }
            db.SaveChanges();
        }
        public void deleteBangDiem(SchoolContext db)
        {
            foreach (var d in db.DiemSo)
            {
                if(d.HocSinhId ==this.Id) { 
                    db.Remove(d);
                }
            }
            db.SaveChanges();
        }
    }
}

Controllers/DiemSoController.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.X509Certificates;

namespace btl_tkweb.Controllers
{
    public class DiemSoController : Controller
    {
        private readonly UserManager<AccountUser> _userManager;
        SchoolContext db;
        public DiemSoController(SchoolContext db,UserManager<AccountUser> userManager)
        {
            _userManager = userManager;
            this.db = db;
        }
        private AccountUser getUser() { return _userManager.GetUserAsync(HttpContext.User).Result; }
        public IActionResult Index(string HocSinhID)
        {
            var user = getUser();
            if (user == null) return NotFound();

            if (user.role == AccountUser.ADMIN)
            {
                var bd = db.DiemSo.Include(m => m.MonHoc).Include(l => l.HocSinh).Where(s => s.HocSinhId.Equals(HocSinhID)).ToList();
                var hs = bd.First().HocSinh;
                ViewBag.HocSinh = hs.Ho + hs.Ten;
                return View(bd);
            }
            if (user.role == AccountUser.GIAOVIEN) { 
                var bd = db.DiemSo
                    .Include(m => m.MonHoc)
                    .Include(l => l.HocSinh)
                    .Where(s => s.HocSinhId.Equals(HocSinhID))
                    .Where(bd=>bd.MonHocID==((GiaoVien)user).MonHocID).ToList();
                var hs = bd.First().HocSinh;
                
                ViewBag.HocSinh = hs.Ho + hs.Ten;
                return View(bd);
            }
            if (user.role == AccountUser.HOCSINH)
            {
                var bd = db.DiemSo.Include(m => m.MonHoc).Include(l => l.HocSinh).Where(s => s.HocSinhId.Equals(HocSinhID)).ToList();
                var hs = bd.First().HocSinh;
                if (hs.Id!=user.Id) return NotFound();
                ViewBag.HocSinh = hs.Ho + hs.Ten;
                return View(bd);
            }
            return NotFound();


        }

        public IActionResult Edit(int id)
        {
            if(id == null || db.DiemSo == null)
            {
                return NotFound();
            }
            var user = getUser();
            if(user == null) { return NotFound(); }
            if(user.role==AccountUser.HOCSINH) { return NotFound(); }
            var bd = db.DiemSo.Find(id);
            if(user.role==AccountUser.GIAOVIEN && 
                !(bd.MonHocID==((GiaoVien)user).MonHocID && db.ChiTietGiangDay.Where(c=>c.GiaoVienID==user.Id).Where(c=>c.LopId == db.HocSinh.Where(hs=>hs.Id==bd.HocSinhId).First().LopID).Count()!=0)
            ) return NotFound();
            if(bd == null)
            {
                return NotFound();
            }
            return View(bd);
        }

        [HttpPost]

        public IActionResult Edit(int id, [Bind("DiemSoID", "MonHocID", "HocSinhId", "DiemHeSo1_1", "DiemHeSo1_3", "DiemHeSo1_2", "DiemHeSo2_1", "DiemHeSo2_2", "DiemHeSo3")] DiemSo ds)
        {
            if (id != ds.DiemSoID)
            {
                return NotFound();
            }
            var user = getUser();
            if (user == null) { return NotFound(); }
            if (user.role == AccountUser.HOCSINH) { return NotFound(); }
            var bd = db.DiemSo.Find(id);
            if (user.role == AccountUser.GIAOVIEN &&
                !(bd.MonHocID == ((GiaoVien)user).MonHocID && db.ChiTietGiangDay.Where(c => c.GiaoVienID == user.Id).Where(c => c.LopId == db.HocSinh.Where(hs => hs.Id == bd.HocSinhId).First().LopID).Count() != 0)
            ) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    var userbd = db.DiemSo.Find(id);
                    userbd.DiemHeSo1_1 = ds.DiemHeSo1_1;
                    userbd.DiemHeSo1_2 = ds.DiemHeSo1_2;
                    userbd.DiemHeSo1_3 = ds.DiemHeSo1_3;
                    userbd.DiemHeSo2_1 = ds.DiemHeSo2_1;
                    userbd.DiemHeSo2_2 = ds.DiemHeSo2_2;
                    userbd.DiemHeSo3 = ds.DiemHeSo3;
                    db.DiemSo.Update(userbd);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    if (!DSexist(ds.DiemSoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new {ds.HocSinhId});
            }
            
            return View(ds);
        }
        private bool DSexist(int id)
        {
            return (db.DiemSo?.Any(e => e.DiemSoID == id)).GetValueOrDefault();
        }

    }
}

Controllers/HocSinhController.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Linq;

namespace btl_tkweb.Controllers
{
    public class HocSinhController : Controller
    {
        int ItemInEachPage = 2;
        SchoolContext db; 
        private readonly SignInManager<AccountUser> _signInManager;
        private readonly UserManager<AccountUser> _userManager;
        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        public HocSinhController(
            UserManager<AccountUser> userManager,
            SignInManager<AccountUser> signInManager,
            SchoolContext db
        ) {
            this.db = db; 
            _userManager = userManager;
            _signInManager = signInManager;
            HocSinh.count = db.HocSinh.Count();
        }
        private AccountUser getUser() { return _userManager.GetUserAsync(HttpContext.User).Result; }
        
        public IActionResult Index(string? LopID, string? name, int page)
        {
            int cnt = db.HocSinh.Count();
            var user = getUser();
            if(user == null)return NotFound();
            if (user.role == AccountUser.HOCSINH && ((HocSinh)user).LopID != LopID) return NotFound();
            if(user.role == AccountUser.GIAOVIEN && db.ChiTietGiangDay.Where(ct=>ct.LopId==LopID&&ct.GiaoVienID==user.Id).Count()==0) return NotFound();
            
;
            if (!string.IsNullOrEmpty(name))
            {
                var hs2 = db.HocSinh.Where(l => l.Ho.Contains(name.Trim()) || l.Ten.Contains(name.Trim())).ToList();
                var pt2 = hs2.Skip((page - 1) * ItemInEachPage).Take(ItemInEachPage).ToList();
                ViewBag.LopID = LopID;
                ViewBag.maxPage = cnt % ItemInEachPage == 0 ? cnt / ItemInEachPage : cnt / ItemInEachPage + 1;
                return View(pt2);
            }
            if (!string.IsNullOrEmpty(LopID))
            {
                var hs = db.HocSinh
                    .Where(hs => hs.LopID.Equals(LopID))
                    /*.OrderBy(s => s.Ten).OrderBy(s => s.Ho)*/
                    .ToList();
                var pt = hs.Skip((page - 1) * ItemInEachPage).Take(ItemInEachPage).ToList();
                ViewBag.LopID = LopID;
                ViewBag.maxPage = cnt % ItemInEachPage == 0 ? cnt / ItemInEachPage : cnt / ItemInEachPage + 1;
                return View(pt);
            }

            
            
            var hs1 = db.HocSinh.ToList();
            var pt1 = hs1.Skip((page-1) * ItemInEachPage).Take(ItemInEachPage).ToList();
            ViewBag.LopID = LopID;

            ViewBag.maxPage = cnt % ItemInEachPage == 0 ? cnt / ItemInEachPage : cnt / ItemInEachPage + 1;
            
            return View(pt1);
           
        }

        public PartialViewResult Test(int page)
        {
            var hs1 = db.HocSinh.ToList();
            var pt1 = hs1.Skip((page - 1) * ItemInEachPage).Take(ItemInEachPage).ToList();
            return PartialView("Table", pt1);
        }
        public IActionResult Create(string? LopID)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();
            
            ViewBag.LopID = LopID;
            return View();
            
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Ho", "Ten", "Nu", "NgaySinh","LopID", "GhiChu")] HocSinh hs,string? LopID)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            ViewBag.LopID = LopID;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (ModelState.IsValid)
            {
                hs.UserName = hs.Username;
                var result = await _userManager.CreateAsync(hs, "Utc@123");

                if (result.Succeeded)
                {
                    var userId = await _userManager.GetUserIdAsync(hs);
                    hs.createBangDiem(db);
                    return RedirectToAction("Index",new {LopID});
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        public IActionResult Edit(string id)
        {
            var user = getUser();
            if (!(
                (user != null && user.role == AccountUser.ADMIN) ||
                (user != null && user.role == AccountUser.HOCSINH && ((HocSinh)user).Id==id)
            )) return NotFound();

            if (id == null || db.HocSinh == null)
            {
                return NotFound();
            }
            var hs = db.HocSinh.Find(id);
            if(hs == null)
            {
                return NotFound();
            }
            ViewBag.LopID = new SelectList(db.Lop, "LopID", "LopID", hs.LopID);
            return View(hs);
        }


        [HttpPost]
        public async Task<IActionResult> EditAsync(string id, [Bind("Id","HocSinhID", "Ho", "Ten", "Nu", "NgaySinh","LopID", "GhiChu")] HocSinh hs)
        {
            var user = getUser();
            if (!(
                (user != null && user.role == AccountUser.ADMIN) ||
                (user != null && user.role == AccountUser.HOCSINH && ((HocSinh)user).Id == id)
            )) return NotFound();

            if (id != hs.Id)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    var userhs = db.HocSinh.First(u => u.Id == hs.Id);
                    userhs.HocSinhID = hs.HocSinhID;
                    userhs.Ho = hs.Ho;
                    userhs.Ten = hs.Ten;
                    userhs.Nu = hs.Nu;
                    userhs.NgaySinh = hs.NgaySinh;
                    userhs.LopID = hs.LopID;
                    userhs.GhiChu = hs.GhiChu;
                    db.HocSinh.Update(userhs);
                    db.SaveChanges();
                    userhs.UserName = userhs.Username;
                    await _userManager.UpdateAsync(userhs);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!Hsexist(hs.HocSinhID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new {hs.LopID});
            }
            ViewBag.LopID = new SelectList(db.Lop, "LopID", "LopID", hs.LopID);
            return View(hs);
        }
        private bool Hsexist(int id)
        {
            return (db.HocSinh?.Any(e => e.HocSinhID == id)).GetValueOrDefault();
        }


        public IActionResult Delete(string id)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (id == null || db.HocSinh == null)
            {
                return NotFound();
            }
            var hs = db.HocSinh.Include(l => l.Lop).Include(e => e.DiemSo).FirstOrDefault(m => m.Id == id);
            if(hs == null)
            {
                return NotFound();
            }
           
            return View(hs);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(string id)
        {
            var user = getUser();
            if (!(user != null && user.role == AccountUser.ADMIN)) return NotFound();

            if (db.HocSinh == null)
            {
                return Problem("Khong con hoc sinh");
            }
            var hs = db.HocSinh.Find(id);
            var lopID = hs.LopID;
            
            if(hs != null)
            {
                hs.deleteBangDiem(db);
                db.HocSinh.Remove(hs);

            }
            db.SaveChanges();
            return RedirectToAction("Index" ,new {lopID});
        }

       
        
    }
}

Views/HocSinh/Create.cshtml
@{
    ViewData["Title"] = "Thêm sinh viên lớp " + ViewBag.LopID;
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

@model HocSinh
<div class="ms-2 mx-2">
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="HocSinh" asp-action="Create" method="post" class="mt-3" novalidate>
        <div style="margin-top:7px" class="form-group row">
            
            <label asp-for="Ho" class="col-sm-2 col-form-label">Họ</label> 
            <div class="col-sm-10">
                 <div class="form-floating">
                    <input asp-for="Ho" class="form-control " placeholder="Ho" , id="Ho" required pattern="[a-zA-Z]{4,20}">
                    <label for="Ho" class="form-label">Họ</label>
                    <div class="invalid-feedback">Không hợp lệ!</div>
                </div>
            </div>
            <span asp-validation-for="Ho" class="text-danger"></span>
        </div>
        <div style="margin-top: 7px" class="form-group row">
            <label asp-for="Ten" class="col-sm-2 col-form-label">Tên</label> 
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="Ten" class="form-control" placeholder="Ten" id="Ten" required pattern="[a-zA-Z]{4,20}" />
                    <label for="Ten">Tên</label>
                    <div class="invalid-feedback">Không hợp lệ!</div>
                </div>
            </div>
            <span asp-validation-for="Ten" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LopID" class="col-sm-2 col-form-label">Lớp học</label> 
            <div class="col-sm-10">
               
               @*  <select asp-for="LopID" class="custom-select mr-sm-2" asp-items="@ViewBag.LopID"></select> *@
                    <input asp-for="LopID" class="form-control form-control-lg" value="@ViewBag.LopID" text="@ViewBag.LopID" id="LopID" />
                   
                
            </div>
            <span asp-validation-for="LopID" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="NgaySinh" class="col-sm-2 col-form-label">Ngày sinh</label> 
            <div class="col-sm-10">
                <input asp-for="NgaySinh" type="date" class="form-control form-control-lg" required />
                <div class="invalid-feedback">Ngày sinh không được bỏ trống!</div>
            </div>
            <span asp-validation-for="NgaySinh" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Nu" class="col-sm-2 col-form-label">Nữ</label>
            <div class="col-sm-10">
                
                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio1" name="Gender" value="true" checked="checked"/>
                    <label for="radio1" class="form-check-label">True</label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="Nu"  type="radio" class="form-check-input" id="radio2" name="Gender" value="false" />
                    <label for="radio2" class="form-check-label">False</label>
                </div>
            </div>
            
            <span asp-validation-for="Nu" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="GhiChu" class="col-sm-2 col-form-label">Ghi chú</label> 
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="GhiChu" class="form-control form-control-lg" id="GhiChu" placeholder="Ghi Chu" required pattern="[a-zA-Z0-9.,]+" />
                    <label for="GhiChu">Ghi chú</label>
                    <div class="invalid-feedback">Ghi chú không đúng</div>

                </div>
            </div>
            <span asp-validation-for="GhiChu" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary" >Thêm học sinh</button>
            </div>
        </div>
    </form>
</div>

<script>
    const form = document.querySelector("form");
    form.addEventListener('submit', e => {
        if (!form.checkValidity()) {
            e.preventDefault()
        }
        form.classList.add('was-validated')
    })
</script>

Views/HocSinh/Delete.cshtml
@{
    ViewData["Title"] = "Xóa sinh viên " + Model.LopID;
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model HocSinh
<div class="ms-2 mx-2">
    
    <h3>Bạn có muốn xóa học sinh này không?(Bảng điểm sẽ được tự động xóa)</h3>
    
    <hr />
    <dl class="row list-group list-group-flush">
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2 ">
                <div class="bg-gradient">Họ</div>
            </dt>
            <dd class="col-sm-10 ">
                @Html.DisplayFor(model => model.Ho)
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradien">Tên</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ten)
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradien">Lớp học</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Lop.LopID)
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradien">Ngày sinh</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.NgaySinh)
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradien">Nữ</div>
            </dt>
            <dd class="col-sm-10">
                @{
                    if(Model.Nu)
                    {
                        <div>True</div>
                    }
                    else
                    {
                        <div>False</div>
                    }
                }
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradien">Ghi chú</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.GhiChu)
            </dd>
        </div>
    </dl>
    <form asp-action="Delete">
        <div class="d-grid gap-2 d-md-block">
            <input type="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Xóa" class="btn btn-danger"/> |
            <a class="btn btn-primary" asp-action="Index" asp-route-lopid="@Model.LopID">Quay lại</a>
        </div>
    </form>
</div>

Views/HocSinh/Edit.cshtml
@{
    ViewData["Title"] = "Cập nhật sinh viên lớp " + Model.LopID;
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model HocSinh
<div class="ms-2 mx-2">
    <div asp-validation-summary="All" class="text-danger"></div> 
    <form asp-controller="HocSinh" asp-action="Edit" asp-route-id="@Model.Id"
                                                                       method="post" class="mt-3" novalidate>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="HocSinhID" />
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Ho" class="col-sm-2 col-form-label">Họ</label> 
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="Ho" class="form-control" placeholder="Ho" id="Ho" required pattern="[a-zA-Z]{4,20}">
                    <label for="Ho">Họ</label>
                    <div class="invalid-feedback">Không hợp lệ!</div>

                </div>
            </div>
            <span asp-validation-for="Ho" class="text-danger"></span>
        </div>
        <div style="margin-top: 7px" class="form-group row">
            <label asp-for="Ten" class="col-sm-2 col-form-label">Tên</label> 
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="Ten" class="form-control" placeholder="Ten" id="Ten" required pattern="[a-zA-Z]{4,20}">
                     <label for="Ten">Tên</label>
                    <div class="invalid-feedback">Không hợp lệ!</div>

                </div>
            </div>
            <span asp-validation-for="Ten" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LopID" class="col-sm-2 col-form-label">Lớp học</label>
            <div class="col-sm-10">
                <select asp-for="LopID" class="custom-select mr-smi-2" asp-items="@ViewBag.LopID"></select>
            </div>
        </div>
        <span asp-validation-for="LopID" class="text-danger"></span>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="NgaySinh" class="col-sm-2 col-form-label">Ngày sinh</label> <div class=" col-sm-10">
                <input asp-for="NgaySinh" class="form-control" required/>
                <div class="invalid-feedback">Ngày sinh không được bỏ trống!</div>

            </div>
            <span asp-validation-for="NgaySinh" class="text-danger"></span>

        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Nu" class="col-sm-2 col-form-label">Nữ</label>
            <div class="col-sm-10">
                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio1" name="Nu" value="true"  checked/>
                    <label for="radio1" asp-for="Nu" class="form-check-label">True</label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio2" name="Nu" value="false" />
                    <label for="radio2"  asp-for="Nu" class="form-check-label">False</label>
                </div>
            </div>
            <span asp-validation-for="Nu" class="text-danger"></span>
        </div>
        <div style="margin-top: 7px" class="form-group row">
            <label asp-for="GhiChu" class="col-sm-2 col-form-label">Ghi chú</label> 
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="GhiChu" class="form-control" placeholder="GhiChu" id="GhiChu" required pattern="[a-zA-Z0-9.,]+">
                    <label for="GhiChu">Ghi chú</label>
                    <div class="invalid-feedback">Ghi chú không đúng</div>

                </div>
            </div>
            <span asp-validation-for="GhiChu" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Sửa</button>
            </div>
        </div>
    </form>
</div>

Views/HocSinh/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<HocSinh>
@{
    ViewData["Title"] = "Học sinh lớp " + ViewBag.LopID;
}
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AccountUser> SignInManager
@inject UserManager<AccountUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}
<form asp-action="Index" method="get" class="form-inline">
    Nhập tên học sinh <input type="text" name="name" /> <button type="submit" class="btn btn-primary">Tìm</button>
</form>
<div class="ms-2 mx-2" >
    <div id="content">
        @{
            Html.RenderPartial("Table");
        }
    </div>
    @if (user.role == AccountUser.ADMIN)
    {
    <a asp-action="Create" asp-route-lopid=@ViewBag.LopID class="btn btn-primary">Thêm học sinh</a>
        
    }

    <select id="val-page" class="custom-select mr-sm-2">=
        @for (int i = 1; i <= ViewBag.maxPage; i++)
        {
            <option value="@i">@i</option>
        }

    </select>
    <button class="btn-page">>></button>
</div>
<script>

    $(".btn-page").click(function (e) {
        var page = $("#val-page").val();
        console.log("Hêlo" + page);   
        $.ajax({
            url: "Hocsinh\\Test",
            data: {page: page},
            success: function (response) {
                $("div#content").html(response);
            }
        })
    })
        
        
</script>

    
</div>

Views/HocSinh/Table.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AccountUser> SignInManager
@inject UserManager<AccountUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Stt</th>
            <th>Họ</th>
            <th>Tên</th>
            <th>Giới tính</th>
            <th>Ngày sinh</th>
            <th>Lớp</th>
            <th>Tên tài khoản</th>
            <th>Ghi chú</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.HocSinhID</td>
                <td>@s.Ho</td>
                <td>@s.Ten</td>
                @{

                    var GioiTinh = "";
                }
                @if (s.Nu) { GioiTinh = "Nữ"; } else { GioiTinh = "Nam"; }
                <td>@GioiTinh</td>
                <td>@s.NgaySinh.ToShortDateString()</td>
                <td>@s.LopID</td>
                <td>@s.UserName</td>
                <td>@s.GhiChu</td>
                @if(user.role == AccountUser.HOCSINH)
                {
                    <td><a asp-controller="DiemSo" asp-action="Index" asp-route-hocsinhid="@s.Id">Bảng điểm</a>
                    </td>
                }
                else
                {
                    <td><a asp-controller="DiemSo" asp-action="Index" asp-route-hocsinhid="@s.Id">Bảng điểm</a>  |  <a asp-action="Edit" asp-route-id="@s.Id">Sửa</a> | <a asp-action="Delete" asp-route-id="@s.Id">Xóa</a></td>
                }



                @* <td><a asp-action="Edit" asp-route-id="@s.LopID">Edit</a> | <a asp-action="Delete" asp-route-id="@s.LopID">Delete</a></td> *@


            </tr>
        }
    </tbody>
</table>