Models/GiaoVien.cs
using Microsoft.EntityFrameworkCore.Design.Internal;
using System.ComponentModel.DataAnnotations;

namespace btl_tkweb.Models
{
    public class GiaoVien : AccountUser
    {
        public static int count=0;
        public GiaoVien()
        {
            ctgd = new HashSet<ChiTietGiangDay>();
            role = GIAOVIEN;
            count++;
            GiaoVienID = count;
        }
        
        public int GiaoVienID { get; set; }

        
        public string HoVaTen { get; set; }

        public bool Nu { get; set; }
        public DateTime NgaySinh { get; set; }
        public int MonHocID { get; set; }
        public virtual MonHoc? MonHoc { get; set; }
        public string? GhiChu { get; set; }
        public  string Username { get { 
                string user = "GV";
                HoVaTen= ""+HoVaTen;
                for (int i = 0; i < HoVaTen.Length; i++)
                {
                    if (HoVaTen[i] == ' ') continue;
                    user += HoVaTen[i];
                }
                user += GiaoVienID ;
                return removeUnicode.RemoveUnicode(user);
        } }
        public virtual ICollection<ChiTietGiangDay> ctgd { get; set; }
    }
}

Controllers/ChiTietGiangDayController.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace btl_tkweb.Controllers
{
    public class ChiTietGiangDayController : Controller
    {
        SchoolContext db;
        private readonly UserManager<AccountUser> _userManager;

        public ChiTietGiangDayController(SchoolContext db, UserManager<AccountUser> _userManager)
        {
            this._userManager = _userManager;
            this.db = db;
        }
        private AccountUser getUser() { return _userManager.GetUserAsync(HttpContext.User).Result; }
        public IActionResult Index(string GiaoVienID)
        {
            var user = getUser();
            if (user == null || user.role != AccountUser.ADMIN) return NotFound();

            var gd = db.ChiTietGiangDay.Include(m => m.Lop).Include(n => n.GiaoVien).Where(l => l.GiaoVienID == GiaoVienID).ToList();
            var gv = db.GiaoVien.Find(GiaoVienID);
            ViewBag.GiaoVien = gv?.HoVaTen;
            ViewBag.GiaoVienID = GiaoVienID;
            return View(gd);
        }


        public IActionResult Create(string GiaoVienID)
        {
            var user = getUser();
            if (user == null || user.role != AccountUser.ADMIN) return NotFound();
            ViewBag.GiaoVienID = GiaoVienID;
            var gd = db.ChiTietGiangDay.Include(m => m.GiaoVien).Where(l => l.GiaoVienID == GiaoVienID).ToList();
            var gv = db.GiaoVien.Find(GiaoVienID);
            ViewBag.GiaoVienID = gv.Id;
            ViewBag.GiaoVienName = gv?.HoVaTen;
            ViewBag.Lop = new SelectList(db.Lop, "LopID", "LopID");
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("GiaoVienID", "LopId")] ChiTietGiangDay ct, string GiaoVienID)
        {
            var user = getUser();
            if (user == null || user.role != AccountUser.ADMIN) return NotFound();
            ViewBag.GiaoVienID = GiaoVienID;
            if (ModelState.IsValid)
            {
                db.ChiTietGiangDay.Add(ct);
                db.SaveChanges();
                
                return RedirectToAction("Index", new { GiaoVienID });
            }
            ViewBag.Lop = new SelectList(db.Lop, "LopID", "LopID");
            return View();
        }

        public IActionResult Delete(int id)
        {
            var user = getUser();
            if (user == null || user.role != AccountUser.ADMIN) return NotFound();
            if (id == null || db.ChiTietGiangDay == null)
            {
                return NotFound();
            }
            var ctgd = db.ChiTietGiangDay.Include(l => l.Lop).Include(e => e.GiaoVien).FirstOrDefault(m => m.ChiTietGiangDayId == id);
            if (ctgd == null)
            {
                return NotFound();
            }
            return View(ctgd);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var user = getUser();
            if (user == null || user.role != AccountUser.ADMIN) return NotFound();
            if (db.ChiTietGiangDay == null)
            {
                return Problem("Khong con chi tiet de xoa");
            }
            var ct = db.ChiTietGiangDay.Find(id);
            var GiaoVienID = ct.GiaoVienID;
            if (ct != null)
            {
                db.ChiTietGiangDay.Remove(ct);
            }
            else
            {
            }
            db.SaveChanges();
            return RedirectToAction("Index", new { GiaoVienID });
        }


    }
}

Controllers/GiaoVienController.cs
using btl_tkweb.Data;
using btl_tkweb.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace btl_tkweb.Controllers
{
    public class GiaoVienController : Controller
    {
        SchoolContext db;
        private readonly SignInManager<AccountUser> _signInManager;
        private readonly UserManager<AccountUser> _userManager;
        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        public GiaoVienController(
            UserManager<AccountUser> userManager,
            SignInManager<AccountUser> signInManager,
            SchoolContext db
        )
        {
            this.db = db;
            _signInManager = signInManager;
            _userManager = userManager;
            GiaoVien.count = db.GiaoVien.Count();
        }
        private AccountUser getUser() { return _userManager.GetUserAsync(HttpContext.User).Result; }
        public IActionResult Index(bool? alert)
        {
            var user = getUser();
            if (user == null)return NotFound();

            if (alert == null) alert = false;
            ViewBag.Alert = alert;

            var gv = db.GiaoVien.Include(s => s.MonHoc).Include(g => g.ctgd).Where(g=>true);
            if (user.role == AccountUser.HOCSINH) gv = gv.Where(g => g.ctgd.Any(c => c.LopId == ((HocSinh)user).LopID));

            var lop = new List<Lop>();
            lop.Add(new Lop() { LopID = "" });
            if(user.role!=AccountUser.HOCSINH)lop.AddRange(db.Lop);
            ViewBag.lopId = new SelectList(lop, "LopID","LopID","");

            var mon= new List<MonHoc>();
            mon.Add(new MonHoc() { MonHocID= 0 ,TenMon="--",HeSoMon=0});
            mon.AddRange(db.MonHoc);
            ViewBag.MonHoc = new SelectList(mon, "MonHocID", "TenMon", "--");

            return View(gv);
        }
        public PartialViewResult Table(string LopID, int? MonHocID)
        {
            var user = getUser();

            if (LopID == "--") LopID = null;
            if(MonHocID==0)MonHocID=null;
            if (LopID == null && MonHocID == null)
            {
                var gv = db.GiaoVien.Include(s => s.MonHoc);
                if (user.role == AccountUser.HOCSINH) return PartialView(gv.Include(g => g.ctgd).Where(g => g.ctgd.Any(c => c.LopId == ((HocSinh)user).LopID)));
                return PartialView(gv);
            }
            else if (LopID == null)
            {
                var gv = db.GiaoVien.Include(s => s.MonHoc).Where(s => s.MonHocID == MonHocID).ToList();
                return PartialView(gv);
            }
            else if (MonHocID == null)
            {
                var gv = db.GiaoVien.Include(s => s.MonHoc).Include(s => s.ctgd).Where(s => s.ctgd.Any(c => c.LopId == LopID)).ToList();
                return PartialView(gv);
            }
            else
            {
                var gv = db.GiaoVien.Include(s => s.MonHoc).Include(s => s.ctgd).Where(s => s.ctgd.Any(c => c.LopId == LopID)).Where(s => s.MonHocID == MonHocID).ToList();
                return PartialView(gv);
            }
        }


        public IActionResult Create()
        {
            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                ViewBag.MonHocID = new SelectList(db.MonHoc, "MonHocID", "TenMon", "");
                return View();
            }
            
            return NotFound();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HoVaTen", "Nu","NgaySinh", "MonHocID","GhiChu")] GiaoVien gv)
        {
            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {

                if (ModelState.IsValid)
                {
                    gv.UserName = gv.Username;
                    var result = await _userManager.CreateAsync(gv, "Utc@123");

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                }
                ViewBag.MonHocID = new SelectList(db.MonHoc, "MonHocID", "TenMon", "");
                return View();
            }
            return NotFound();
            
        }

        public IActionResult Edit(string id)
        {

            var user = getUser();
            if (user != null && ((user.role == AccountUser.ADMIN)||(user.role==AccountUser.GIAOVIEN && user.Id==id)))
            {
                if (id == null || db.GiaoVien == null)
                {
                    return NotFound();
                }
                var gv = db.GiaoVien.Find(id);
                if (gv == null)
                {
                    return NotFound();
                }
                ViewBag.MonHocID = new SelectList(db.MonHoc, "MonHocID", "TenMon", gv.MonHocID);
                return View(gv);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(string id, [Bind("Id","GiaoVienID", "HoVaTen", "Nu", "NgaySinh", "MonHocID", "GhiChu")] GiaoVien gv)
        {

            var user = getUser();
            if (user != null && ((user.role == AccountUser.ADMIN) || (user.role == AccountUser.GIAOVIEN && user.Id == id)))
            {
                if (id != gv.Id)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        var dbuser = db.GiaoVien.First(u => u.Id == gv.Id);
                        dbuser.GiaoVienID = gv.GiaoVienID;
                        dbuser.HoVaTen = gv.HoVaTen;
                        dbuser.Nu = gv.Nu;
                        dbuser.NgaySinh = gv.NgaySinh;
                        dbuser.MonHocID = gv.MonHocID;
                        dbuser.GhiChu = gv.GhiChu;
                        dbuser.UserName = dbuser.Username;
                        db.GiaoVien.Update(dbuser);
                        db.SaveChanges();
                        await _userManager.UpdateAsync(dbuser);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!Gvexist(gv.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction("Index");
                }
                ViewBag.MonHocID = new SelectList(db.MonHoc, "MonHocID", "TenMon", gv.MonHocID);
                return View(gv);
            }
            return NotFound();
        }
        private bool Gvexist(string id)
        {
            return (db.GiaoVien?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public IActionResult Delete(string id)
        {

            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (id == null || db.GiaoVien == null)
                {
                    return NotFound();
                }
                var gv = db.GiaoVien.Include(l => l.MonHoc).Include(e => e.ctgd).FirstOrDefault(m => m.Id == id);
                if (gv == null)
                {
                    return NotFound();
                }
                if (gv.ctgd.Count() > 0)
                {
                    return RedirectToAction("Index", new { alert = true });
                }
                return View(gv);
            }
            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(string id)
        {

            var user = getUser();
            if (user != null && user.role == AccountUser.ADMIN)
            {
                if (db.GiaoVien == null)
                {
                    return Problem("Khong con giao vien");
                }
                var gv = db.GiaoVien.Find(id);


                if (gv != null)
                {
                    db.GiaoVien.Remove(gv);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

    }
}

Views/GiaoVien/Create.cshtml
@{
    ViewData["Title"] = "Thêm giáo viên";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

@model GiaoVien
<div class="ms-2 mx-2">
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="GiaoVien" asp-action="Create" method="post" class="mt-3" novalidate >
        <div style="margin-top:7px" class="form-group row">

            <label asp-for="HoVaTen" class="col-sm-2 col-form-label">Họ và tên</label>
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="HoVaTen" class="form-control " placeholder="Ho" , id="HoVaTen" required pattern="[a-zA-Z]{4,20}">
                    <label for="HoVaTen" class="form-label">Họ và Tên</label>
                    <div  class="invalid-feedback">Tên không chính xác</div>
                </div>
            </div>
            <span asp-validation-for="HoVaTen" class="text-danger"></span>
        </div>
        
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MonHocID" class="col-sm-2 col-form-label">Lớp học</label>
            <div class="col-sm-10">

                 <select asp-for="MonHocID" class="form-select mr-sm-2" asp-items="@ViewBag.MonHocID" required></select> 


            </div>
            <span asp-validation-for="MonHocID" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="NgaySinh" class="col-sm-2 col-form-label">Ngày sinh</label>
            <div class="col-sm-10">
                <input asp-for="NgaySinh" class="form-control form-control-lg" required />
                <div class="invalid-feedback">Ngày tháng không được bỏ trống</div>
            </div>
            <span asp-validation-for="NgaySinh" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Nu" class="col-sm-2 col-form-label">Nữ</label>
            <div class="col-sm-10">

                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio1" name="Gender" value="true" checked="checked" />
                    <label for="radio1" class="form-check-label">True</label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio2" name="Gender" value="false" />
                    <label for="radio2" class="form-check-label">False</label>
                </div>
            </div>

            <span asp-validation-for="Nu" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="GhiChu" class="col-sm-2 col-form-label">Ghi chú</label>
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="GhiChu" class="form-control form-control-lg" id="GhiChu" placeholder="GhiChu" required pattern="[a-zA-Z0-9.,]+" />
                    <label for="GhiChu">Ghi chú</label>
                    <div class="invalid-feedback">Ghi chú không đúng</div>
                </div>
            </div>
            <span asp-validation-for="GhiChu" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Thêm giáo viên</button>
            </div>
        </div>
    </form>
</div>

<script>
    const form = document.querySelector("form");
    form.addEventListener('submit', e => {
        if (!form.checkValidity()) {
            e.preventDefault()
        }
        form.classList.add('was-validated')
    })
</script>

Views/GiaoVien/Delete.cshtml
@{
    ViewData["Title"] = "Xóa giáo viên ";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model GiaoVien
<div class="ms-2 mx-2">

    <h3>Are you sure you want to delete this?</h3>

    <hr />
    <dl class="row list-group list-group-flush">
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2 ">
                <div class="bg-gradient">Họ và tên</div>
            </dt>
            <dd class="col-sm-10 ">
                @Html.DisplayFor(model => model.HoVaTen)
            </dd>
        </div>
        
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradient">Lớp học</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MonHoc.MonHocID)
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradient">Ngày sinh</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.NgaySinh)
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradient">Nữ</div>
            </dt>
            <dd class="col-sm-10">
                @{
                    if (Model.Nu)
                    {
                        <div>True</div>
                    }
                    else
                    {
                        <div>False</div>
                    }
                }
            </dd>
        </div>
        <div class="list-group-item list-group-item-action">
            <dt class="col-sm-2">
                <div class="bg-gradient">Ghi chú</div>
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.GhiChu)
            </dd>
        </div>
    </dl>
    <form asp-action="Delete">
        <div class="d-grid gap-2 d-md-block">
            <input type="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            <a class="btn btn-primary" asp-action="Index" >Quay lại</a>
        </div>
    </form>
</div>

Views/GiaoVien/Edit.cshtml
@{
    ViewData["Title"] = "Cập nhật giáo viên";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model GiaoVien
<div class="ms-2 mx-2">
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="GiaoVien" asp-action="Edit" asp-route-id="@Model.Id"
          method="post" class="mt-3" novalidate>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="GiaoVienID" />
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="HoVaTen" class="col-sm-2 col-form-label">Họ và tên</label>
            <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="HoVaTen" class="form-control " placeholder="Ho" , id="HoVaTen" required pattern="[a-zA-Z]{4,20}">
                    <label for="HoVaTen" class="form-label">Họ và Tên</label>
                    <div class="invalid-feedback">Tên không chính xác</div>
                </div>
            </div>
            <span asp-validation-for="HoVaTen" class="text-danger"></span>
        </div>
        
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MonHocID" class="col-sm-2 col-form-label">Lớp học</label> <div class="col-sm-10">
                <select asp-for="MonHocID" class="custom-select mr-smi-2" asp-items="@ViewBag.MonHocID"></select>
            </div>
        </div>
        <span asp-validation-for="MonHocID" class="text-danger"></span>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="NgaySinh" class="col-sm-2 col-form-label">Ngày sinh</label> <div class=" col-sm-10">
                <input asp-for="NgaySinh" class="form-control" required/>
                <div class="invalid-feedback">Ngày tháng không được bỏ trống</div>
            </div>
            <span asp-validation-for="NgaySinh" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Nu" class="col-sm-2 col-form-label">Nữ</label>
            <div class="col-sm-10">
                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio1" name="Nu" value="true" checked />
                    <label for="radio1" asp-for="Nu" class="form-check-label">True</label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="Nu" type="radio" class="form-check-input" id="radio2" name="Nu" value="false" />
                    <label for="radio2" asp-for="Nu" class="form-check-label">False</label>
                </div>
            </div>
            <span asp-validation-for="Nu" class="text-danger"></span>
        </div>
        <div style="margin-top: 7px" class="form-group row">
            <label asp-for="GhiChu" class="col-sm-2 col-form-label">Ghi chú</label> <div class="col-sm-10">
                <div class="form-floating">
                    <input asp-for="GhiChu" class="form-control form-control-lg" id="GhiChu" placeholder="GhiChu" required pattern="[a-zA-Z0-9.,]+" />
                    <label for="GhiChu">Ghi chú</label>
                    <div class="invalid-feedback">Ghi chú không đúng</div>
                </div>
            </div>
            <span asp-validation-for="GhiChu" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Sửa</button>
            </div>
        </div>
    </form>
</div>
<script>
    const form = document.querySelector("form");
    form.addEventListener('submit', e => {
        if (!form.checkValidity()) {
            e.preventDefault()
        }
        form.classList.add('was-validated')
    })
</script>

Views/GiaoVien/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Giáo Viên";
}
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AccountUser> SignInManager
@inject UserManager<AccountUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}
@model IEnumerable<GiaoVien>

<div class="ms-2 mx-2">
    @if (ViewBag.Alert)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">Giáo viên còn chi tiết chưa xóa </div>
    }
    <div class="m-3">
        Lớp: <select id="lophoc" class="custom-select mr-sm-2" asp-items="@ViewBag.LopID"></select>
    </div>
    <div class="m-3">
        Môn học: <select id="monhoc" class="custom-select mr-sm-2" asp-items="@ViewBag.MonHoc"></select>
    </div>
    <div id="content">
        @{Html.RenderPartial("Table");}
    </div>
    @if (user.role == AccountUser.ADMIN)
    {
     <a asp-action="Create" class="btn btn-primary">Thêm giáo viên</a>
        
    }
    
</div>
@section Scripts{
    <script>
        $("select#lophoc, select#monhoc").on('change',createTable);
        function createTable (e) {
            var lopid = $("select#lophoc").val();
            var monid = $("select#monhoc").val();
            console.log(lopid);
            $.ajax({
                url: '@Url.Action("table","GiaoVien")',
                data: { LopID: lopid, MonHocID: monid },
                success: function (response) {
                    console.log("test");
                    $("div#content").html(response);
                }
            },);
        }
    </script>
}

Views/GiaoVien/Table.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AccountUser> SignInManager
@inject UserManager<AccountUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Stt</th>
            <th>Họ và tên</th>
            <th>Giới tính</th>
            <th>Ngày sinh</th>
            <th>Môn học</th>
            <th>Tên tài khoản</th>
            <th>Ghi chú</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            var stt = 0;
            stt +=1;
            <tr>
                <td>@stt</td>
                <td>@s.HoVaTen</td>
                @{
                    var GioiTinh = "";
                }
                @if (s.Nu) { GioiTinh = "Nữ"; } else { GioiTinh = "Nam"; }
                <td>@GioiTinh</td>
                <td>@s.NgaySinh</td>
                <td>@s.MonHoc.TenMon</td>
                <td>@s.UserName</td>
                <td>@s.GhiChu</td>
                @if(user.role == AccountUser.GIAOVIEN)
                {
                    <td> <a asp-controller="ChiTietGiangDay" asp-action="Index" asp-route-giaovienid="@s.Id">Chi tiết giảng dạy</a></td>
                }
                @if (user.role == AccountUser.ADMIN)
                {
                    <td> <a asp-controller="ChiTietGiangDay" asp-action="Index" asp-route-giaovienid="@s.Id">Chi tiết giảng dạy</a> |  <a asp-action="Edit" asp-route-id="@s.Id">Sửa</a> | <a asp-action="Delete" asp-route-id="@s.Id">Xóa</a></td>
                    
                }
            </tr>
        }
    </tbody>
</table>